### ISSUE TITLE
Migrate pandas append to pandas concat

### ISSUE THREAD

**Issue by jornfranke** [ZuInnoTe/scrapy-contrib-bigexporters#4]
Migrate pandas append to pandas concat

Reason: Append is deprecated since 1.4.0 in pandas

cf. 
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.append.html

and
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.concat.html#pandas.concat

**Comment by isaacimholt** [comment]
Any updates?

**Comment by jornfranke** [comment]
Will come soon

**Comment by jornfranke** [comment]
will be part of 0.4.0
