### ISSUE TITLE
Flush sooner

### ISSUE THREAD

**Issue by amircohere** [ZuInnoTe/scrapy-contrib-bigexporters#9]
With larger scrapes sometimes it helps to flush the file sooner instead of flushing all in one big file. It would help to do the following:

```python
FEEDS = {
    's3://aws_key:aws_secret@mybucket/data-%(name)s-%(time)s-%(shard_num)s.parquet': {
        'format': 'parquet',
        'encoding': 'utf8',
        'store_empty': False,
        'item_export_kwargs': {
            'compression': 'GZIP',
            'file_split_threshold': 20_000,  # Split after 20k rows
        },
    }
}
```

and then we can pass in shard name in the file.

**Comment by amircohere** [comment]
Hmmm the correct way for this seems to be:
https://docs.scrapy.org/en/2.11/topics/feed-exports.html#feed-export-batch-item-count

**Comment by jornfranke** [comment]
Hi, thanks for the feedback. I agree that batch-item count is probably the standard way. 
Does it fit to your requirement? If so then please close the issue.
Otherwise please let me know what is missing from batch-item count

**Comment by amircohere** [comment]
Yep that seemed to have solved the issue, looks like this now

```python
FEEDS = {
    's3://aws_key:aws_secret@mybucket/data-%(name)s-%(time)s-%(batch_id)05s.parquet': {
        'format': 'parquet',
        'encoding': 'utf8',
        'store_empty': False,
        'item_export_kwargs': {
            'compression': 'GZIP',
        },
    }
}
FEED_EXPORT_BATCH_ITEM_COUNT = 10_000
```
